### ISSUE TITLE
How can deploy in public ip in droplet Ubuntu 20?

### ISSUE THREAD

**Issue by johnfelipe** [adpextwindong/Last-Viewer#3]

**Comment by adpextwindong** [comment]
Have you tried building it locally. I dont do that droplet shit.

**Comment by johnfelipe** [comment]
Pls share a cheatsheet completly for deploy locally in VMware Ubuntu 20.
Stay alert.

**Comment by adpextwindong** [comment]
pls share your build experience locally with npm before doing a driveby issue, K thnx bye

**Comment by adpextwindong** [comment]
This isn't to offend people potentially interested in this project but looking at your Github activity @johnfelipe all you do is spam issues on open projects with zero invested effort.

**Comment by johnfelipe** [comment]
I want to try, but your answer is very good tnks a lot
